name: Build and Deploy to EKS

on:
  push:
    branches:
      - developer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: us-east-2

      - name: Build and push frontend image
        run: |
          docker build -t my_app_frontend:latest -f frontend/Dockerfile ./frontend
          docker tag my_app_frontend:latest ${{ steps.login-ecr.outputs.registry }}/my_app_frontend:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/my_app_frontend:latest

      - name: Build and push backend image
        run: |
          docker build -t my_app_backend:latest -f backend/Dockerfile ./backend
          docker tag my_app_backend:latest ${{ steps.login-ecr.outputs.registry }}/my_app_backend:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/my_app_backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: v1.21.0

      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --name my-cluster --region us-east-1

      - name: Deploy to EKS
        run: |
          kubectl set image deployment/frontend-deployment frontend=${{ steps.login-ecr.outputs.registry }}/my_app_frontend:latest
          kubectl set image deployment/backend-deployment backend=${{ steps.login-ecr.outputs.registry }}/my_app_backend:latest
